[package]
authors = [
  "Paul Fornage <paul@fornage.net>",
  "Karsten Große <karsten.grosse@sympatron.de>",
  "John Little <johngigantic@gmail.com>",
]
categories = ["embedded", "hardware-support", "no-std"]
description = "Board Support crate for the ClearCore"
edition = "2021"
keywords = ["no-std", "arm", "cortex-m", "embedded-hal"]
license = "MIT OR Apache-2.0"
name = "clearcore"
readme = "README.md"
repository = "https://github.com/paul-fornage/atsamd"
version = "0.13.4"

[dependencies.cortex-m-rt]
optional = true
version = "0.7"

[dependencies.cortex-m]
features = ["critical-section-single-core"]
version = "0.7"

[dependencies.atsamd-hal]
default-features = false
path = "../../hal"
version = "0.23.4"

[dependencies.usb-device]
optional = true
version = "0.3.1"

[dev-dependencies]
rtic = {version = "2.1.2", features = ["thumbv7-backend"]}
panic-probe = {version = "1.0.0", features = ["print-rtt"] }
rtt-target = {version = "0.6.2"}
usbd-serial = "0.2"

[features]
default = ["rt", "atsamd-hal/same53n"]
dma = ["atsamd-hal/dma"]
max-channels = ["dma", "atsamd-hal/max-channels"]
# Enable async support from atsamd-hal
async = ["atsamd-hal/async"]
can = ["atsamd-hal/can"]
rt = ["cortex-m-rt", "atsamd-hal/same53n-rt"]
usb = ["atsamd-hal/usb", "usb-device"]
# Enable rtic support from atsamd-hal
rtic = ["atsamd-hal/rtic"]

[[example]]
name = "blinky_basic"

[[example]]
name = "hello_world"

[[example]]
name = "blinky_rtic"
required-features = ["rtic"]

[[example]]
name = "hello_world_usb"
required-features = ["usb"]